name: CI

on:
  pull_request:
  push:
      branches:
      - master

jobs:
  run-tests:
    runs-on: [ubuntu-latest]

    env:
        DEEPSOURCE_DSN_PROD: ${{ secrets.DEEPSOURCE_DSN_PROD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up python3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Run tests
      run: |
        pip install pytest-cov django
        pytest --cov=./ --cov-report=xml
        
    - name: Add git safe.directory for container
      run: |
        mkdir -p /home/runner/work/_temp/_github_home
        printf "[safe]\ndirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig

    - name: Report test-coverage to DeepSource
      uses: deepsourcelabs/test-coverage-action@master
      with:
        key: python
        coverage-file: ./coverage.xml
        dsn: ${{ secrets.DEEPSOURCE_DSN_PROD }}
        
#     - name: Report test coverage to DeepSource prod (python, js)  
#       run: |
#         curl https://deepsource.io/cli | sh
#         export DEEPSOURCE_DSN=$DEEPSOURCE_DSN_PROD
#         ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
        
        
